# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 Tomas Laurenzo

if(NOT EXISTS "${PRESET_FILE}")
    message(FATAL_ERROR "Voicing preset file is missing: ${PRESET_FILE}")
endif()

file(READ "${PRESET_FILE}" json)
string(JSON schema ERROR_VARIABLE error GET "${json}" schemaVersion)
if(error OR NOT schema EQUAL 1)
    message(FATAL_ERROR "Voicing preset schemaVersion must be 1: ${error}")
endif()
string(JSON count ERROR_VARIABLE error LENGTH "${json}" presets)
if(error OR NOT count EQUAL 12)
    message(FATAL_ERROR "Expected 12 voicing presets, found ${count}: ${error}")
endif()

set(ids)
set(independent_count 0)
set(chord_count 0)
set(strum_count 0)
set(valid_scales major naturalMinor dorian phrygian lydian mixolydian locrian majorPentatonic minorPentatonic blues chromatic hungarianMinor wholeTone diminished)
set(valid_pitch radius nearest plane speed phase radialVelocity relativeSpeed acceleration angularMomentum)
set(valid_trigger clock plane close turning apsis receding speedPeak phaseStep)

math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    string(JSON id GET "${json}" presets ${index} id)
    list(FIND ids "${id}" duplicate)
    if(id STREQUAL "" OR NOT duplicate EQUAL -1)
        message(FATAL_ERROR "Voicing preset ${index} has an empty or duplicate id: ${id}")
    endif()
    list(APPEND ids "${id}")

    string(JSON mode GET "${json}" presets ${index} mode)
    if(mode STREQUAL "independent")
        math(EXPR independent_count "${independent_count} + 1")
    elseif(mode STREQUAL "chord")
        math(EXPR chord_count "${chord_count} + 1")
    elseif(mode STREQUAL "strum")
        math(EXPR strum_count "${strum_count} + 1")
    else()
        message(FATAL_ERROR "Voicing preset ${id} has invalid mode: ${mode}")
    endif()

    string(JSON density GET "${json}" presets ${index} density)
    if(density LESS 0 OR density GREATER 100)
        message(FATAL_ERROR "Voicing preset ${id} density is out of range")
    endif()
    string(JSON voice_count LENGTH "${json}" presets ${index} voices)
    if(NOT voice_count EQUAL 3)
        message(FATAL_ERROR "Voicing preset ${id} must define three voices")
    endif()

    foreach(voice RANGE 0 2)
        string(JSON channel GET "${json}" presets ${index} voices ${voice} channel)
        string(JSON root GET "${json}" presets ${index} voices ${voice} root)
        string(JSON minimum GET "${json}" presets ${index} voices ${voice} minimum)
        string(JSON maximum GET "${json}" presets ${index} voices ${voice} maximum)
        string(JSON scale GET "${json}" presets ${index} voices ${voice} scale)
        string(JSON pitch GET "${json}" presets ${index} voices ${voice} pitch)
        string(JSON trigger GET "${json}" presets ${index} voices ${voice} trigger)
        string(JSON duration_min GET "${json}" presets ${index} voices ${voice} durationMin)
        string(JSON duration_max GET "${json}" presets ${index} voices ${voice} durationMax)
        list(FIND valid_scales "${scale}" scale_index)
        list(FIND valid_pitch "${pitch}" pitch_index)
        list(FIND valid_trigger "${trigger}" trigger_index)
        if(channel LESS 1 OR channel GREATER 16 OR root LESS 0 OR root GREATER 11
           OR minimum LESS 0 OR maximum GREATER 127 OR minimum GREATER maximum
           OR scale_index EQUAL -1 OR pitch_index EQUAL -1 OR trigger_index EQUAL -1
           OR duration_min LESS 0.125 OR duration_max GREATER 8 OR duration_min GREATER duration_max)
            message(FATAL_ERROR "Voicing preset ${id} voice ${voice} contains an invalid enum or range")
        endif()
    endforeach()
endforeach()

if(NOT independent_count EQUAL 4 OR NOT chord_count EQUAL 4 OR NOT strum_count EQUAL 4)
    message(FATAL_ERROR "Voicing presets must contain four entries per mode")
endif()
